### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by mhalano** [porridge/command-runner-applet#3]
When executed on Ubuntu with Unity this program doesn't appears among other indicators. I think there is a little of code to add support to this program work as a indicator.

**Comment by porridge** [comment]
I don't use Unity. Can you provide some screenshots on where the program is visible and the places where it's missing so I know what you're talking about?

**Comment by mhalano** [comment]
The icon should be on the top-left corner together with other icons, clock and so on, but there is no icon. That's because Unity doesn't use gnome-panel anymore, but indicators.


![command-runner](https://cloud.githubusercontent.com/assets/6025031/18251906/5c3c9424-7362-11e6-8bdf-ebb34eaac591.png)

**Comment by porridge** [comment]
I cannot see any icons in the top-left corner. I'm going to assume you
meant top-right.
It's interesting that in your example command_runner does not crash.
Perhaps it's just waiting for gnome-panel to come to life - you could check
that by looking at syslog.

Anyway, unfortunately - unless indicators provide some panel-compatible API
- I'm not going to implement this, all the more that I do not run an
environment where I could test it.
Someone determined enough could probably port it, though.

**Comment by mhalano** [comment]
Yeah, indeed is top-right. My mistake. :)
You could see some documentation on https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators
The command-runner-applet on Ubuntu is useless because there is no icon.

May be someone with knowledge could create a patch.

**Comment by porridge** [comment]
I wouldn't go as far to say it's useless on Ubuntu as a whole. I use it on
Ubuntu with Gnome classic/flashback.
